require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CostCategoriesController do

  def mock_cost_category(stubs={})
    @mock_cost_category ||= mock_model(CostCategory, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cost_categories as @cost_categories" do
      CostCategory.stub(:all) { [mock_cost_category] }
      get :index
      assigns(:cost_categories).should eq([mock_cost_category])
    end
  end

  describe "GET show" do
    it "assigns the requested cost_category as @cost_category" do
      CostCategory.stub(:find).with("37") { mock_cost_category }
      get :show, :id => "37"
      assigns(:cost_category).should be(mock_cost_category)
    end
  end

  describe "GET new" do
    it "assigns a new cost_category as @cost_category" do
      CostCategory.stub(:new) { mock_cost_category }
      get :new
      assigns(:cost_category).should be(mock_cost_category)
    end
  end

  describe "GET edit" do
    it "assigns the requested cost_category as @cost_category" do
      CostCategory.stub(:find).with("37") { mock_cost_category }
      get :edit, :id => "37"
      assigns(:cost_category).should be(mock_cost_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cost_category as @cost_category" do
        CostCategory.stub(:new).with({'these' => 'params'}) { mock_cost_category(:save => true) }
        post :create, :cost_category => {'these' => 'params'}
        assigns(:cost_category).should be(mock_cost_category)
      end

      it "redirects to the created cost_category" do
        CostCategory.stub(:new) { mock_cost_category(:save => true) }
        post :create, :cost_category => {}
        response.should redirect_to(cost_category_url(mock_cost_category))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cost_category as @cost_category" do
        CostCategory.stub(:new).with({'these' => 'params'}) { mock_cost_category(:save => false) }
        post :create, :cost_category => {'these' => 'params'}
        assigns(:cost_category).should be(mock_cost_category)
      end

      it "re-renders the 'new' template" do
        CostCategory.stub(:new) { mock_cost_category(:save => false) }
        post :create, :cost_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cost_category" do
        CostCategory.stub(:find).with("37") { mock_cost_category }
        mock_cost_category.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cost_category => {'these' => 'params'}
      end

      it "assigns the requested cost_category as @cost_category" do
        CostCategory.stub(:find) { mock_cost_category(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cost_category).should be(mock_cost_category)
      end

      it "redirects to the cost_category" do
        CostCategory.stub(:find) { mock_cost_category(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cost_category_url(mock_cost_category))
      end
    end

    describe "with invalid params" do
      it "assigns the cost_category as @cost_category" do
        CostCategory.stub(:find) { mock_cost_category(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cost_category).should be(mock_cost_category)
      end

      it "re-renders the 'edit' template" do
        CostCategory.stub(:find) { mock_cost_category(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cost_category" do
      CostCategory.stub(:find).with("37") { mock_cost_category }
      mock_cost_category.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cost_categories list" do
      CostCategory.stub(:find) { mock_cost_category }
      delete :destroy, :id => "1"
      response.should redirect_to(cost_categories_url)
    end
  end

end
